---
title: "Pokemon Go Catch Rate Calculator"
author: "Mark Litak"
date: "5/4/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# INTRODUCTION

## What

In this project, a catch chance calculator for Pokemon Go Generation I Pokemon was created. In addition to calculating the probability for a catch on any given throw, the number of throws before the player has an 80% chance of catching the Pokemon is given, as well as the number of throws before the Pokemon has a 50% chance of fleeing.

## Why

This topic was chosen because I am a Pokemon Go player, and when we were talking about geometric distributions, this automatically came to mind. I had seen Pokemon Catch Chance calculators before, and I wanted to try my hand at creating one. However, I have never seen a catch chance calculator that also determined the number of throws before a likely failure or success.

## How

### Formula
On the Pokemon wiki, a formula for the Probability of Catching a Pokemon is provided, as well as several data tables for use with the formula,

$$ P = 1 - (1 - \frac{BCR}{2 \times CPM})^{Ball \times Berry \times Throw \times Curveball \times Medal \times Encounter}$$

where BCR is the **Base Catch Rate**, provided in a table, **CPM** is the CP multiplier, **Ball** is the type of ball used to attempt to catch the Pokemon, **Throw** corresponds to a specific throw's accuracy, **Curveball** is whether a player threw a curveball or not, **Medal** is whether the player has a medal in that specific Pokemon's type, and **Encounter**, corresponding to whether the player encountered the Pokemon in the Wild or through some other means, such as a Raid.

Within this project, several assumptions were made. 

* The Pokemon was assumed to have been encountered in the Wild, as the Wild contains Pokemon with the highest possible levels; this corresponds to an exponent multiplier of $1$. 
* The Pokemon was assumed to be the highest level possible with such an encounter (level 35, corresponding to a CP multiplier of $0.7615638$). 
* The player was assumed to successfully throw a curveball, which is not particularly difficult with practice; this corresponds to a multiplier of $1.7$. 
* The player is assumed to not have a medal in the type, corresponding to a multiplier of $1$.

With the above assumptions, the formula used became

$$ P = 1 - (1 - \frac{BCR}{2 \times 1.52312768})^{1.7 \times Ball \times Berry \times Throw}$$
## Ball, Berry, and Throw Modifiers

In the exponent are several variables which change the roll modifier.

There are three types of balls, each corresponding to different modifiers within the formula. **Pokeballs** are normal balls, and their modifier is 1; it does not change the probability. **Great balls** are rarer, and their corresponding modifier is 1.5. **Ultra balls** are the rarest and most difficult to acquire, and their corresponding modifier is 2.

Additionally, there are several types of berries, three of which change the modifier. **Razz Berries** give a modifier of 1.5. **Silver Pinap Berries**, or Silver berries for short, give a modifier of 1.8. **Golden Razz Berries** give a modifier of 1.5.

Finally, there are four types of throws. **Normal** throws do not change the probability, as their modifier is 1. The modifier for a **nice** throw ranges from 1 to 1.3, depending on how accurately a ball is thrown; the average of 1.15 was taken in this calculator. The modifier for a **great** throw ranges from 1.3 to 1.7, and thus 1.5 was the modifier chosen in this calculator. **Excellent** throws give between 1.7 and 2 as a modifier, and therefore 1.85 was chosen as their modifier.

### Number of Throws Before Success or Failure

For the purposes of this program, **success** was defined as a catch, and **failure** was defined as the Pokemon running away.

To determine the number of throws before a likely success (or a likely failure), the R function `qgeom` was used. A "likely success" was determined to be an 80% chance of having succeeded. A "likely failure," on the other hand, was determined to be a 50% chance of failure.

# Body

## Introduction to Pokemon Go

Pokemon Go is an augmented reality game, played on mobile phones, which allows a player to experience the Pokemon games in their surroundings. Pokemon spawn across the world, and the player attempts to catch the Pokemon with Pokeballs, which they may obtain at PokeStops and Gyms, tied to real-life landmarks. Players also obtain Berries, objects that they may "feed" a Pokemon. Some berries make catching a Pokemon easier.

When playing Pokemon Go, a player needs to manage their Pokeballs and their Berries, and may sometimes be in danger of running out of them. Some Pokeballs are rarer and more difficult to acquire, though they provide a higher chance of catching a Pokemon. Additionally, catching a Pokemon becomes more difficult the higher its level is. A Pokemon displays its CP above its head when a player encounters it; this CP corresponds to that particular Pokemon's level.

A rough estimate of catch chance is given by a colored circle when catching a Pokemon, but this is a rough estimate. A calculator for a precise catch chance, as well as the number of throws before an 80% chance of success, was created in order to facilitate Pokeball and Berry management. Additionally, as Pokemon may also flee before they are caught, a figure for the number of throws before the Pokemon flees is also provided, to give the player a good idea of how many throws they can truly risk before failure.

## Challenges

A number of challenges arose in creating this Catch Chance Calculator. Formatting the data for Base Catch Rates proved difficult, as did determining which variables to include in the program, and which to keep constant.

The first challenge in creating this calculator was acquiring the data for Base Catch Rates, and formatting it properly for R to interpret. I ended up needing to manually enter this data into Excel from a Pokemon Wiki page, as attempting to copy paste from a table proved strangely difficult; images of the Pokemon were unable to be removed when copy-pasting. After manual entry, I converted the Base Catch Rate data into a CSV and opened it in R.

Upon considering the Catch Rate formula, I realized that several variables were present. Some of these variables I discarded outright for simplicity, such as Encounter type and whether or not the player had a Medal; I assumed that the most difficult option would be the case. As learning how to throw curveballs may take only a few attempts, as this is simple enough, I felt that I could safely assume that the player would be throwing a curveball. 

However, this still left me with five variables. I knew that the most popular calculator made a table, of the type of ball to be used and the accuracy of a throw, with checkboxes for berries, and a slider for the Pokemon's level. I knew that I wanted to keep a rudimentary User Interface, with an option for the chosen Pokemon. I considered whether I wanted to keep the CPM a variable, or if I wanted to keep it at a constant level, and whether I wanted to keep the Berry a constant variable as well, or if I wanted to assume that the player was using no berry (or a Razz berry, which provides a modifier of $1.5$, the lowest of the available berries). 

After a short period of consideration, I decided to keep the Berry choice, as this would add only a comparatively low amount of complexity. I debated whether I should leave this as an option for the user to choose initially, along with the Pokemon's number, or if I wanted to create a tensor, or 3D table, with the data immediately visible slice by slice. Ultimately, I decided that choosing a berry to use initially would be the simplest approach to take; however, taking a more complex approach may be possible with more work to be done.

The question of CPM was both easier and more difficult. Initially, I very much wanted to have an option for the user that would allow them to input the CP of the Pokemon, have the program calculate the level of the Pokemon and therefore its CPM, and then determine the catch rate based on this. However, upon further research, I discovered that the CP of a Pokemon and its level vary tremendously, and listings of this data were poorly formatted for copy-pasting; therefore, having some sort of table or data frame with that information would require a large amount of manual input. AS a result, I opted to choose the most difficult possible level for a Wild encounter, Level 35.

As mentioned above, one point of improvement that I would like to make in the future is rather than asking the player to input their berry *before* a calculation is made, the data would be provided to give the player a chance to compare how many throws they can risk with the number of throws until a likely failure. This would be done by making several tables, which can be made with a `for` loop. The display of these tables in a legible and easily-comparable manner may prove to be another challenge, as four Throwing tables would need to be displayed, in addition to a Probability table and a Failure figure. A longer-term goal would be to grant the player the ability to manually input a Pokemon's CP, and allow the program to vary accordingly. 

However, a catch chance calculator that allows its user to see the number of throws before a likely success, and compare it to the number of throws before a likely failure, gives an opportunity for the player to see how easily a Pokemon can run away, and how many attempts they are likely to get before a success or failure.

# Topics From Class

## RMarkdown

Creating files in RMarkdown was not significantly difficult to me. Through my previous degree in math, I have experience in writing Markdown files with LaTeX, as many homework assignments were required in such a format.

## Github

On the other hand, Github is not something that I am very familiar with. I learned a lot in trying to create a Repository for this project, which I had only done once previously.

## Geometric Distribution

To determine both the number of throws before a likely success (probability of 80% or more) and the number of throws before pokemon will likely run away (probability of 50% or more), a geometric distribution was necessary. A geometric distribution is a distribution corresponding to the probability of failure given some number of trials. This was discussed in class as a helpful tool in probability and statistics.

## R: Qgeom

The function that was used, `qgeom(X,Y)`, corresponds to a sum of the values of the geometric distribution until reaching the desired percentile. It determines the number of failures before a probability of success `X` is found, given a probability of success per trial `Y`. This function was also discussed and used in class as a helpful tool in probability and statistics.

## R: Creating Functions in R

In order to make the R script function, it was necessary to create functions. I created three: a function to replicate the P formula listed above, a function to calculate the number of throws necessary to likely catch a Pokemon (with a probability of .8), and a function to calculate how many throws before a Pokemon will likely run away (with a probabilty of .5). These functions were created in R, and the entire course was exploring concepts in probability and statistics using R.

# Conclusion

This project was very interesting, and through it, I became more comfortable using the geometric distribution and its related function in R, `qgeom`. Additionally, I learned a lot about formatting in R, creating functions, and creating and formatting tables for the user's perusal. I also learned more about scripting in R, which I had not been doing throughout class, preferring instead to use RMarkdown. This allowed me to make a rudimentary command line-based User Interface. In addition to learning about R topics, I learned a lot about the subject matter which I was analyzing. Through running several trials, I learned that, in most cases, even with the weakest ball and no berries used, the number of throws before a likely catch will still be higher than the number of throws before a Pokemon runs away. I also, of course, learned how the catch probability is calculated.

Had I had more time, instead of creating only a single table and requiring a user to input the type of berry used, if any, I would have instead displayed four tables with catch chances and the number of throws necessary to have a likely success. If the data had been easier to format, or I had a *lot* more time, I would have included a calculator for a Pokemon's CP and its corresponding level, and included that in the catch chance calculation.

# Sources

Information about the probability formula, catch rates, and CP modifiers was taken from the Pokemon Wiki, Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Catch_rate_(GO)

I refreshed my memory on `qgeom`, c(), cbind(), and making tables was taken from Statology.
https://www.statology.org/dgeom-pgeom-qgeom-rgeom-r/
https://www.statology.org/c-function-in-r/
https://www.statology.org/create-table-in-r/

I refreshed my memory on making functions using https://swcarpentry.github.io/r-novice-inflammation/02-func-R/

I learned how to take user input from https://www.datamentor.io/r-programming/examples/user-input/

